### ISSUE TITLE
请问怎么使用？

### ISSUE THREAD

**Issue by Annnnh1010** [Twiyin0/koishi-plugin-imgupload#1]
![VeryCapture_20240322225920](https://github.com/Twiyin0/koishi-plugin-imgupload/assets/76246787/54a85188-16ad-4316-bc26-c40a70383c2c)

**Comment by Annnnh1010** [comment]
![VeryCapture_20240322225920](https://github.com/Twiyin0/koishi-plugin-imgupload/assets/76246787/53ab66cf-378e-4eb1-8335-a62f50dbfc79)

**Comment by Twiyin0** [comment]
用法1. 
> imgupload [一个图片url/一张/多张图片]（注: 图片目前有bug，还未修复）

用法2. 
> imgupload
> [一张图片]

用法3.
> imgupload -c
> [图片1]
> [图片2]
> [图片3]
> [图片4]
> $
